name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - id: 0fd9d0bd-2eca-499c-9905-548372cf2254
            name: clawdius
          - id: a01eeef9-6eed-449e-a36f-f0fe8ae60d85
            name: clawbo
    name: Deploy ${{ matrix.app.name }}
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Trigger deployment
        run: doctl apps create-deployment ${{ matrix.app.id }} --wait=false
